// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Author struct {
	ID    int32
	Email string
	Bio   sql.NullString
}

type Book struct {
	ID              int32
	Title           string
	PublicationDate time.Time
	AuthorID        int32
}
